import discord

class Texts(): # Contains all the information which will be deployed in the bot
# Requerimientos Main
  hola_message = discord.Embed(title="Quien soy?", description="Hola! me llamo @FerMIT y soy el bot de la Facultad de Matemáticas, mi misión es ayudarte en caso de que necesites encontrar información sobre algunos procesos escolares que necesites durante tu proyecto en tu carrera\n\n Puedes escribir !comandos para descubrir lo que puedo ofrecerte",color=0x0CA6EA)
  
  comandos_message = discord.Embed(title="Que buscas?", description="Aquí te presento los comandos para solicitar información, escribe alguno para ayudarte.\n\n !tramites: Para visualizar la información de los principales trámites que ofrece la facultad\n\n !mapa: No te perderás más dentro de tu facultad, obtén el croquis para obtener información\n\n !informacion: Para visualizar informacion importante referente a algunos procesos de la facultad de matematicas",color=0x0B26D3)

  mapas_message = discord.Embed(title="Mapa de FMAT", description="",color=0xffffff) #croquis de la facultad.

  calendario_message = discord.Embed(title="Calendario 2022-2023", description="Este es el Calendario Enero-Julio2022: https://www.matematicas.uady.mx/files/control-escolar/2022/02/2022-02-09_calendario-mefi-enero-julio-2022.pdf",color=0xFF370D)

  tramites_message = discord.Embed(title="Tramites", description="Lista de comandos de tramites:\n\n -  ",color=0xffffff) #Colocar lista de comandos

#Requerimientos Tramites
  revalidacion_message = discord.Embed(title="Tramites - Revalidacion", description="Si eres estudiante admitido a la universidad y cursaste tu bachillerato en alguna escuela ajena a la UADY, entonces necesitarás revalidar tus estudios, pero no te preocupes, estoy aquí para guiarte durante todo el proceso.\n\nLos documentos que necesitarás para realizar tu revalidación exitosamente son: \n1.Certificado de estudios de secundaria (original)\n2.Certificado de estudios completos de bachillerato. (original).\nEn caso de haber estudiado en más de una institución, adicionalmente deberás entregar:\n  - Certificados parciales expedidos por cada una de las instituciones donde hayas estudiado.\n   - Copia del oficio de revalidación emitido por la SEP (en caso de haber estudiado en el extranjero).\n  - Copia del oficio de equivalencia ( en caso de haber estudiado dentro del país).\n\nNota: En caso de que el certificado completo no tenga la fecha de inicio y fin de estudios de bachillerato, se deberá entregar adicionalmente una constancia expedida por la escuela en donde se mencionen esos datos.\n\n3. Los derechos educativos con sus respectivos comprobantes de pago:\n   - Derecho de revalidación de bachillerato completo ($810).\n    - Derecho de legalización de fotostáticas ($50).\nPuedes acceder a la siguietne liga para hacer el pago de los derechos:\nhttp://www.sii.uady.mx/derechos/\n\n Una vez que ya tengas todos tus documentos completos, deberás realizar los siguientes pasos:\n1. Dirigirte al siguiente link: https://www.cgse.uady.mx/citasodr/?rt=2&progKey=REVBC\n ",color=0xffffff)

  revalidacion_message_2 = discord.Embed( description="2. Posteriormente deberás llenar el folio de registro del examen de selección y verificar/llenar los datos que se piden en la solicitud de revalidación.\n3. Guardar los datos introducidos.\n4. Una vez guardados los datos te llegará un correo con un usuario y contraseña para que puedas acceder al sistema de revalidación.\n5. Subir todos los documentos mencionados anteriormente, ya sea en formato digital PDF o documento digitalizado/escaneado.\n6. Recibirás un correo de confirmación que dice que has iniciado el trámite de revalidación, el personal revisará todos tus documentos durante los meses de agosto y septiembre, en caso de tener problemas con algún documento o que este esté incompleto, se notificará al correo ingresado. En caso de tener todo en orden, entre octubre y noviembre te notificarán para que puedas descargar tu oficio de revalidación electrónico.\n\n¡Y listo! Si requieres más información puedes ingresar al siguiente link: \nhttps://revalidacion.uady.mx/#/revalidacion",color=0xffffff)
  
  inscripcion_message = discord.Embed(title="Tramites - Inscripcion", description="¡Muchas felicidades, estás a un paso de ser parte de la UADY! para esto déjame ayudarte con el primer proceso que harás en tu facultad, la inscripción.\nPara esto necesitarás los siguientes documentos:",color=0xffffff) ##AGREGAR EL DOCUMENTO QUE ESTÁ EN EL LINK

  reinscripcion_message = discord.Embed(title="Tramites - Reinscripcion", description="¡Ya huele a otro semestre en la facultad! para poder verte el siguiente semestre necesitas seguir los pasos para completar la reinscripción, te dejo aquí abajo los pasos y requisitos:\nLa reinscripción consta de 3 pasos principales:\n\n    1. Inscripción administrativa: Debes llenar tu hoja estadística y hacer el pago del semestre. ($800). Todo esto dentro de SICEI.\n\n    2. Inscripción académica: Realizar tu carga académica en SICEI, es decir, seleccionar tus profesores y horarios del semestre !haz la mejor elección¡\n\n    3. Entrega de documentos: Los documentos que deberás entregar son:\n        - Horario firmado (puedes imprimir tu horario, firmarlo y posteriormente escanearlo).\n        - Comprobante de pago de inscripción al semestre, incluyendo tu nombre, carrera y matrícula en la parte de enfrente. En caso de llevar acompañamiento MEFI, deberás agregar el comprobante de pago de cada acompañamiento incluyendo tu nombre, matrícula, carrera y nombre de la asignatura.\n\nLink de acceso al SICEI:  http://www.sicei.uady.mx/siceiweb/",color=0xffffff)

  descargaLibres_message = discord.Embed(title="Tramites - Descarga de libres", description="Lista de comandos de tramites:\n\n",color=0xffffff) #Info

  descargaOptativas_message = discord.Embed(title="Tramites - Descarga de optativas", description="Lista de comandos de tramites:\n\n",color=0xffffff) #Info
  
  constancia_message = discord.Embed(title="Constancias", description="¡Justo tengo la información que necesitas!\nPara obtener una constancia de estudios debes acudir al Departamento de Contabilidad de la Facultad de Matemáticas en horario de 10:00 - 17:00, ahí deberás hacer un pago de $10 y te entregarán el comprobante de pago que posteriormente deberás registrar en el siguiente link: \nhttps://goo.gl/CUk9WT\nUna vez hayas registrado tu comprobante de pago, deberás esperar de 3 a 5 días hábiles para ir a recoger tu constancia al Departamento de Control Escolar dentro de los horarios establecidos: 10:00 - 13:30 o 16:00 - 19:00.\n!Y listo, así de fácil es obtener tu constancia de estudios!",color=0xffffff)

  titulacionMEFI_message = discord.Embed(title="Tramite - Titulacion-MEFI", description="¡Muy bien!, solo te recuerdo que el método de titulación MEFI está disponible para las carreras de:\n\nActuaría\nCiencias de la Computación\nEnseñanza de las Matemáticas\nIngeniería de Software\nIngeniería en Computación\n\n Me ayudarías mucho diciéndome el método por el cual egresarás.\n\n !egel\n !tesis\n !titulodirecto\n",color=0xffffff) #info

  tituEGEL_message = discord.Embed(title="Tramite - Titulacion-EGEL", description="¡Excelente! antes de continuar te comento que la titulación por medio de EGEL está disponible solo para las siguientes carreras:\n\n Ciencias de la Computación.\n Ingeniería en computación.\n Ingeniería de Software.\n\n Si te quieres titular mediante el Examen General de Egreso de Licenciatura primero debes haber cubierto los siguientes requisitos: \n\n Haber concluido las condiciones de pasantía establecidas por tu plan de estudios.\n Tener un documento que acredite un desempeño satisfactorio en al menos el 50% de las áreas que conforman el EGEL. \n\n Si ya cumpliste con estos requisitos, puedes solicitar la autorización para titularse por medio del EGEL a través de la siguiente liga: \n\n https://forms.gle/4VYK1Yt598wdRfS88 \n\n Tu solicitud deberá ser autorizada en no más de 5 días hábiles.\n\n Una vez que tengas tu aprobación, deberás entregar los siguientes documentos en Control Escolar para solicitar tu título: \n\n Oficio de autorización para titularse en esta modalidad.\n Acta de nacimiento. \n Original del Certificado de Estudios de Licenciatura. (puedes escribir !certificado para mayor información). \n Original del Certificado de Estudios de Bachillerato y, en su caso, Oficio de Revalidación. \n Copia de tu CURP actualizada. \n Carta de terminación de prácticas profesionales. \n Certificado original de Servicio Social. \n Constancias de no adeudo en los Departamentos de Contabilidad, Cómputo y Biblioteca (puedes escribir !adeudoconta y !adeudobiblio para mayor información). \n Derecho de Constancia de Exención de Examen Profesional. (puedes obtenerlo a través de: http://www.sii.uady.mx/derechos/). \n Derecho de Título de Licenciatura Electrónico. (puedes obtenerlo a través de: http://www.sii.uady.mx/derechos/). \n Original de la solicitud “Título Profesional Electrónico” de la UADY (puedes ver más información aquí: http://www.titulacion.uady.mx/index.php?s=tra ).",color=0xffffff)

  tituTesis_message = discord.Embed(title="Tramite - Titulacion-TESIS", description="¡Muy bien! si te vas a titular por tesis, primero debes haber cubierto los siguientes requisitos:\n\n Haber concluido las condiciones de pasantía establecidas por tu plan de estudios.\n Haber realizado la defensa de tesis.\n\n Si ya cumpliste con estos requisitos, puedes solicitar la autorización para titularse por medio de tesis a través de la siguiente liga: \n\n https://forms.gle/4VYK1Yt598wdRfS88 \n\n Tu solicitud deberá ser autorizada en no más de 5 días hábiles.\n\n Una vez que tengas tu aprobación, deberás entregar los siguientes documentos en Control Escolar para solicitar tu título: \n\n Oficio de autorización para titularse en esta modalidad.\n Acta de nacimiento. \n Original del Certificado de Estudios de Licenciatura. (puedes escribir !certificado para mayor información). \n Original del Certificado de Estudios de Bachillerato y, en su caso, Oficio de Revalidación. \n Copia de tu CURP actualizada. \n Carta de terminación de prácticas profesionales. \n Certificado original de Servicio Social. \n Constancias de no adeudo en los Departamentos de Contabilidad, Cómputo y Biblioteca (puedes escribir !adeudoconta y !adeudobiblio para mayor información). \n Copia electrónica del trabajo de tesis. \n Derecho de Constancia de Exención de Examen Profesional. (puedes obtenerlo a través de: http://www.sii.uady.mx/derechos/). \n Derecho de Título de Licenciatura Electrónico. (puedes obtenerlo a través de: http://www.sii.uady.mx/derechos/). \n Original de la solicitud “Título Profesional Electrónico” de la UADY (puedes ver más información aquí: http://www.titulacion.uady.mx/index.php?s=tra ).",color=0xffffff)

  tituDirecta_message = discord.Embed(title="Tramite - Titulacion-Directa", description="¡Magnífico! antes de continuar te comento que la titulación directa está disponible solo para las siguientes carreras:\n\n Actuaría.\n Enseñanza de las matemáticas\n\n Si te quieres titular por este medio, primero debes haber cubierto los siguientes requisitos: \n\n Haber concluido las condiciones de pasantía establecidas por tu plan de estudios.\n\n Si ya cumpliste con estos requisitos, puedes solicitar la autorización para titularse por este medio a través de la siguiente liga: \n\n https://forms.gle/4VYK1Yt598wdRfS88 \n\n Tu solicitud deberá ser autorizada en no más de 5 días hábiles.\n\n Una vez que tengas tu aprobación, deberás entregar los siguientes documentos en Control Escolar para solicitar tu título: \n\n Oficio de autorización para titularse en esta modalidad.\n Acta de nacimiento. \n Original del Certificado de Estudios de Licenciatura. (puedes escribir !certificado para mayor información). \n Original del Certificado de Estudios de Bachillerato y, en su caso, Oficio de Revalidación. \n Copia de tu CURP actualizada. \n Carta de terminación de prácticas profesionales. \n Certificado original de Servicio Social. \n Constancias de no adeudo en los Departamentos de Contabilidad, Cómputo y Biblioteca (puedes escribir !adeudoconta y !adeudobiblio para mayor información). \n Derecho de Constancia de Exención de Examen Profesional. (puedes obtenerlo a través de: http://www.sii.uady.mx/derechos/). \n Derecho de Título de Licenciatura Electrónico. (puedes obtenerlo a través de: http://www.sii.uady.mx/derechos/). \n Original de la solicitud “Título Profesional Electrónico” de la UADY (puedes ver más información aquí: http://www.titulacion.uady.mx/index.php?s=tra ).",color=0xffffff)

  adeudoConta_message = discord.Embed(title="Tramite - Adeudo de contabilidad", description="En caso de que necesites una carta de no adeudo de contabilidad o una carta de no adeudo de centro de cómputo, puedes dirigirte al siguiente enlace en donde hay un formulario que deberás llenar con tus datos.\n\nLink:https://www.matematicas.uady.mx/76-facultad/secretaria-academica/600-constancia-de-no-adeudo-del-centro-de-computo-y-contabilidad\n\nUna vez que hayas mandado la información, deberás esperar alrededor de 3 días hábiles para que te manden el documento solicitado al correo que hayas ingresado. ¡Mucha suerte!\n\nNota: Si estás en tu proceso de titulación, deberás tramitar dichos documentos en el siguiente enlace: https://forms.gle/o9qarRcLqfPqfmCz9",color=0xffffff)

  adeudoBiblio_message = discord.Embed(title="reinscripcion", description="Si deseas obtener una constancia de no adeudo de biblioteca, es muy fácil, lo único que debes hacer es dirigirte al siguiente  enlace:\n\nhttps://forms.office.com/Pages/ResponsePage.aspx?id=dNmEfTpwz0S3kpA8o9uAQ0juQ4tYz_1OtJUYUmMbH6hUMkk0Q0w2T0E5MlFEQ0VMWEpMMVZVQ1ZCWC4u\n\nPosteriormente solo deberás llenarlo con algunos datos que ya sabes. ¡Y listo! Pronto deberás tener tu carta de no adeudo de la biblioteca.",color=0xffffff)

  revalidacionCIL_message = discord.Embed(title="reinscripcion", description="Seguramente cursaste Inglés en una institución ajena al CIL, pero no hay problema porque puedes hacer el trámite de tu Carta de Acreditación de Inglés.\n\nSemestre Enero - Mayo:\nLas fechas en las que puedes registrarte para realizar el trámite son:\n8 y 15 de febrero\n8, 15 y 29 de marzo\n26 de abril\n17 y 24 de mayo\n\nEl registro se llevará a cabo en: https://cil.uady.mx/\n\nSi te deseas registrar usando documentos externos (De una institución ajena al CIL) debes registrarte en el siguiente enlace: \n https://forms.gle/HnyC7cSGyX95cB666 Si deseas registrarte mediante el resultado de un Examen TOEFL ITP del CIL accede al siguiente enlace:  https://forms.gle/2chi4Kdep8TUYVmD9 \nSi deseas más información sobre los documentos necesarios, proceso completo o las fechas de los resultados puedes acceder al siguiente documento:",color=0xffffff)
#AGREGAR EL DOCUMENTO QUE ESTÁ EN EL LINK:

# Requerimientos de Informacion de Importancia
  bajasAcademicas_message = discord.Embed(title="bajas-academicas", description="Si tienes dudas sobre las bajas académicas no te preocupes, aquí te explico de manera sencilla.\n\n Realmente en la universidad no existe la baja temporal, solo existe la baja definitiva.\n La baja definitiva es cuando realizas el trámite para ya no pertenecer más a tu plan de estudios. Posteriormente puedes entrar a cualquier otra licenciatura que desees, pero ya no podrás entrar a la misma. ¡Piensa muy bien antes de hacerlo!\n\n Por otra parte, la “baja temporal” no requiere de ningún trámite, si deseas darte un descanso de la universidad puedes “darte de baja” temporalmente simplemente omitiendo el proceso de reinscripción a tu siguiente semestre, de este modo tu matrícula seguirá registrada en el sistema de la universidad.",color=0xffffff)


  ciscoAcademy_message = discord.Embed(title="CISCOAcademy", description="La UADY mediante la alianza con CISCO, nos ofrece una gran variedad de cursos enfocados para las áreas de computación en donde podrás desarrollar destrezas y conseguir certificaciones reconocidas internacionalmente. Si quieres saber más sobre los cursos que ofrece CISCO Academy puedes consultar el siguiente enlace:\n\n https://intranet.matematicas.uady.mx/personal/enrique.ayala/web/cisco/ \n\n Si deseas inscribirte a algún curso CISCO puedes contactar con los siguientes profesores de acuerdo con los cursos que imparten:\n\n Para el curso IT Essentials: \n\n María del Carmen Zozaya Ayuso\n Ernesto Solís Ordoñez \n Fernando Cobá Arias\n\n Para los cursos CCNA R&S: \n\n En FMAT Mérida: \n\n Enrique Ayala Franco\n Sergio Cervera Loeza \n Rodrigo Esparza Sánchez \n En la Unidad Multidisciplinaria Tizimín: \n Lizzie Narváez Díaz\n Víctor Manuel Chi Pech \n\n ¡No dudes en aprovecharlo!",color=0xffffff)


  bloquesCarga_message = discord.Embed(title="bloques-carga-academica", description="Sin complicaciones, los bloques de carga son los distintos momentos en los que los alumnos cargarán en SICEI sus materias para el siguiente semestre. En la Facultad de Matemáticas hay 2 grupos de carga de asignaturas:\n\n - Primer grupo: Los que se encuentran aquí son alumnos que no deben ninguna asignatura hasta el momento, es decir, han acreditado todas sus asignaturas previas. \n Usualmente ellos cargan a las 8:00 am en el día establecido.\n\n - Segundo grupo: Son aquellos que deben una o más asignaturas, los que se encuentren aquí cargarán más tarde y por ende, tienen menos posibilidad de tomar con el profesor(a) de su preferencia.\n Usualmente ellos cargan posterior al medio día.",color=0xffffff)