import discord

class Texts(): # Contains all the information which will be deployed in the bot
  
  help_message = discord.Embed(title="Quien soy?", description="Hola! me llamo @FerMIT y soy el bot de la Facultad de Matemáticas, mi misión es ayudarte en caso de que necesites encontrar información sobre algunos procesos escolares que necesites durante tu proyecto en tu carrera\n\n Puedes escribir !comandos para descubrir algunos de mis comandos",color=0xffffff)
  
  comandos_message = discord.Embed(title="Comandos", description="Aquí te presento los comandos para solicitar información, escribe alguno para ayudarte.\n !tramites: Para visualizar la información de los principales trámites que ofrece la facultad\n !becas: Para informarte sobre las principales becas institucionales vigentes.\n !mapa: No te perderás más dentro de tu facultad, obtén el croquis para obtener información",color=0xffffff)
  
  inscripcion_message = discord.Embed(title="Inscripcion", description="¡Muchas felicidades, estás a un paso de ser parte de la UADY! para esto déjame ayudarte con el primer proceso que harás en tu facultad, la inscripción.\nPara esto necesitarás los siguientes documentos:",color=0xffffff) ##AGREGAR EL DOCUMENTO QUE ESTÁ EN EL LINK

  constancia_message = discord.Embed(title="Constancias", description="¡Justo tengo la información que necesitas!\nPara obtener una constancia de estudios debes acudir al Departamento de Contabilidad de la Facultad de Matemáticas en horario de 10:00 - 17:00, ahí deberás hacer un pago de $10 y te entregarán el comprobante de pago que posteriormente deberás registrar en el siguiente link: \nhttps://goo.gl/CUk9WT\nUna vez hayas registrado tu comprobante de pago, deberás esperar de 3 a 5 días hábiles para ir a recoger tu constancia al Departamento de Control Escolar dentro de los horarios establecidos: 10:00 - 13:30 o 16:00 - 19:00.\n!Y listo, así de fácil es obtener tu constancia de estudios!",color=0xffffff)
  
  reinscripcion_message = discord.Embed(title="reinscripcion", description="¡Ya huele a otro semestre en la facultad! para poder verte el siguiente semestre necesitas seguir los pasos para completar la reinscripción, te dejo aquí abajo los pasos y requisitos:\nLa reinscripción consta de 3 pasos principales:\n\n    1. Inscripción administrativa: Debes llenar tu hoja estadística y hacer el pago del semestre. ($800). Todo esto dentro de SICEI.\n\n    2. Inscripción académica: Realizar tu carga académica en SICEI, es decir, seleccionar tus profesores y horarios del semestre !haz la mejor elección¡\n\n    3. Entrega de documentos: Los documentos que deberás entregar son:\n        - Horario firmado (puedes imprimir tu horario, firmarlo y posteriormente escanearlo).\n        - Comprobante de pago de inscripción al semestre, incluyendo tu nombre, carrera y matrícula en la parte de enfrente. En caso de llevar acompañamiento MEFI, deberás agregar el comprobante de pago de cada acompañamiento incluyendo tu nombre, matrícula, carrera y nombre de la asignatura.\n\nLink de acceso al SICEI:  http://www.sicei.uady.mx/siceiweb/",color=0xffffff)
  
  revalidacion_message = discord.Embed(title="reinscripcion", description="Si eres estudiante admitido a la universidad y cursaste tu bachillerato en alguna escuela ajena a la UADY, entonces necesitarás revalidar tus estudios, pero no te preocupes, estoy aquí para guiarte durante todo el proceso.\n\nLos documentos que necesitarás para realizar tu revalidación exitosamente son: \n1.Certificado de estudios de secundaria (original)\n2.Certificado de estudios completos de bachillerato. (original).\nEn caso de haber estudiado en más de una institución, adicionalmente deberás entregar:\n  - Certificados parciales expedidos por cada una de las instituciones donde hayas estudiado.\n   - Copia del oficio de revalidación emitido por la SEP (en caso de haber estudiado en el extranjero).\n  - Copia del oficio de equivalencia ( en caso de haber estudiado dentro del país).\n\nNota: En caso de que el certificado completo no tenga la fecha de inicio y fin de estudios de bachillerato, se deberá entregar adicionalmente una constancia expedida por la escuela en donde se mencionen esos datos.\n\n3. Los derechos educativos con sus respectivos comprobantes de pago:\n   - Derecho de revalidación de bachillerato completo ($810).\n    - Derecho de legalización de fotostáticas ($50).\nPuedes acceder a la siguietne liga para hacer el pago de los derechos:\nhttp://www.sii.uady.mx/derechos/\n\n Una vez que ya tengas todos tus documentos completos, deberás realizar los siguientes pasos:\n1. Dirigirte al siguiente link: https://www.cgse.uady.mx/citasodr/?rt=2&progKey=REVBC\n ",color=0xffffff)
  
  revalidacion_message_2 = discord.Embed(title="reinscripcion", description="2. Posteriormente deberás llenar el folio de registro del examen de selección y verificar/llenar los datos que se piden en la solicitud de revalidación.\n3. Guardar los datos introducidos.\n4. Una vez guardados los datos te llegará un correo con un usuario y contraseña para que puedas acceder al sistema de revalidación.\n5. Subir todos los documentos mencionados anteriormente, ya sea en formato digital PDF o documento digitalizado/escaneado.\n6. Recibirás un correo de confirmación que dice que has iniciado el trámite de revalidación, el personal revisará todos tus documentos durante los meses de agosto y septiembre, en caso de tener problemas con algún documento o que este esté incompleto, se notificará al correo ingresado. En caso de tener todo en orden, entre octubre y noviembre te notificarán para que puedas descargar tu oficio de revalidación electrónico.\n\n¡Y listo! Si requieres más información puedes ingresar al siguiente link: \nhttps://revalidacion.uady.mx/#/revalidacion",color=0xffffff)
  
  adeudoconta_message = discord.Embed(title="reinscripcion", description="En caso de que necesites una carta de no adeudo de contabilidad o una carta de no adeudo de centro de cómputo, puedes dirigirte al siguiente enlace en donde hay un formulario que deberás llenar con tus datos.\n\nLink:https://www.matematicas.uady.mx/76-facultad/secretaria-academica/600-constancia-de-no-adeudo-del-centro-de-computo-y-contabilidad\n\nUna vez que hayas mandado la información, deberás esperar alrededor de 3 días hábiles para que te manden el documento solicitado al correo que hayas ingresado. ¡Mucha suerte!\n\nNota: Si estás en tu proceso de titulación, deberás tramitar dichos documentos en el siguiente enlace: https://forms.gle/o9qarRcLqfPqfmCz9",color=0xffffff)
  
  adeudobiblio_message = discord.Embed(title="reinscripcion", description="Si deseas obtener una constancia de no adeudo de biblioteca, es muy fácil, lo único que debes hacer es dirigirte al siguiente  enlace:\n\nhttps://forms.office.com/Pages/ResponsePage.aspx?id=dNmEfTpwz0S3kpA8o9uAQ0juQ4tYz_1OtJUYUmMbH6hUMkk0Q0w2T0E5MlFEQ0VMWEpMMVZVQ1ZCWC4u\n\nPosteriormente solo deberás llenarlo con algunos datos que ya sabes. ¡Y listo! Pronto deberás tener tu carta de no adeudo de la biblioteca.",color=0xffffff)
  
  revalidacioncil_message = discord.Embed(title="reinscripcion", description="Seguramente cursaste Inglés en una institución ajena al CIL, pero no hay problema porque puedes hacer el trámite de tu Carta de Acreditación de Inglés.\n\nSemestre Enero - Mayo:\nLas fechas en las que puedes registrarte para realizar el trámite son:\n8 y 15 de febrero\n8, 15 y 29 de marzo\n26 de abril\n17 y 24 de mayo\n\nEl registro se llevará a cabo en: https://cil.uady.mx/\n\nSi te deseas registrar usando documentos externos (De una institución ajena al CIL) debes registrarte en el siguiente enlace: \n https://forms.gle/HnyC7cSGyX95cB666 Si deseas registrarte mediante el resultado de un Examen TOEFL ITP del CIL accede al siguiente enlace:  https://forms.gle/2chi4Kdep8TUYVmD9 \nSi deseas más información sobre los documentos necesarios, proceso completo o las fechas de los resultados puedes acceder al siguiente documento:",color=0xffffff) 